### ISSUE TITLE
Add support of from/to properties for global time compression

### ISSUE THREAD

**Issue by LudwigCRON** [LudwigCRON/pywave#19]
in  the following toml is accepted.
```toml
[[annotations]]
shape = "||"
x = 2.5
```
However when using groups or spacer to have a blank line, the global time compression is behind possible other annotations. It make diagram difficult to read.

One could add several global time compression for each group such that the blank space is preserved and readability too.

Supporting from/to properties would results in something like below

```toml
[[annotations]]
shape = "||"
x = 2.5
from = 3
to = 7

[[annotations]]
shape = "||"
x = 2.5
from = 9
to = 12
```
