### ISSUE TITLE
global hscale and annotations

### ISSUE THREAD

**Issue by LudwigCRON** [LudwigCRON/pywave#23]
On experiment is seems global hscale is not considered for the positionning of the annotations.
Therefore it does not consider local hscale too ?

![image](https://user-images.githubusercontent.com/2118740/86326426-f9ea4f00-bc41-11ea-8eb2-c99b71189dce.png)
```yml
annotations:
    - shape: "|"
      x: 2.15
      stroke-dasharray: [1, 3]
      stroke: "#db4141"
    - shape: "|"
      x: 3.0
      stroke-dasharray: [1, 3]
      stroke: "#db4141"
    - shape: "<->"
      from: (2.15, 3)
      to: (3, 3)
      text: "T   "
      dy: -0.2
      dx: -0.2
      fill: "#db4141"
      stroke: "#db4141"
      font-size: 0.4em

config:
    hscale: 0.5

```
