### ISSUE TITLE
text background crop arrows

### ISSUE THREAD

**Issue by LudwigCRON** [LudwigCRON/pywave#24]
the background of the text crop the arrow
![image](https://user-images.githubusercontent.com/2118740/86328004-70884c00-bc44-11ea-9c24-a7d9de81c9c3.png)

so either make transparent background
or create a layer management and add text in lower layer

**Comment by LudwigCRON** [comment]
The background improve readability of text over large arrows. So the background is kept.
However, one can disable the background with `text_background` as follows:
```yaml
annotations:
  - shape: "<->"
    from: (2.15, 3)
    to: (3, 3)
    text: "Tnov"
    text_background: False
```
This solution is introduced for the coming release v0.0.4 in the commit d498aea0e2ce95f2ae0456b6a486d5e901a58e4f
